- hosts: all
  become: yes
  tasks:
    - name: Install repo key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
        state: present
    - name: Add Jenkins repository
      sudo: yes
      apt_repository: repo='{{ jenkins.deb.repo }}' state=present update_cache=yes
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes
    - name: Start and enable the Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
    - name: Install required packages
      apt: name={{ item }} state=present
      with_items:
        - git
        - phpunit
